### ISSUE TITLE
How to update UI after handling click by view? 

### ISSUE THREAD

**Issue by ghost** [fraggjkee/DataBindingRecyclerAdapter#2]
In my app I have RecyclerView with VK feed posts, but I have some problem. When I'm trying to hadle a click by like button, I can't update UI (likes count near to like button in specific RecyclerView item). 
What I've tried:

**FeedViewModel**
```kotlin
private fun onSuccessPosts(posts: List<VKWallPost>) { // feed post request success
    feedPosts.value = posts
        .map { it.toBindingPost(groupName.value.orEmpty(), groupPhoto.value.orEmpty()) }
        .map { createPostModel(it) } // here is like callback and Post POJO
        .map { it.toRecyclerItem() }
}

private fun onSuccessLike(post: Post, likes: VKWallPost.Like) { // like request success
    val items = feedPosts.value.orEmpty()
    val index = items.map { it.data }
        .filterIsInstance<FeedPostModel>()
        .indexOfFirst { it.post.id == post.id }
    if (index != -1) {
        feedPosts.value = items.toMutableList().also { // Wanna change like image and count in TextView
            (it[index].data as FeedPostModel).post.likeFromUser = true
            (it[index].data as FeedPostModel).post.likes = likes.likes.toString() // result of the likes quantity after clicking on the btnLike
        }
    }
}
```
**FeedPostModel**
```kotlin
class FeedPostModel(val post: Post) {

    lateinit var likeClick: (post: Post) -> Unit

    fun onLikeClick() {
        likeClick.invoke(post)
    }
}
```
**feed_item.xml**
```xml
        <xyz.hanks.library.bang.SmallBangView
            android:id="@+id/btnLike"
            android:layout_width="24dp"
            android:layout_height="24dp"
            android:layout_marginStart="16dp"
            android:layout_marginTop="12dp"
            android:layout_marginBottom="8dp"
            android:onClick="@{() -> vm.onLikeClick()}"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/postViewPager">

            <ImageView
                android:id="@+id/imageLike"
                style="@style/ImageView"
                android:layout_width="24dp"
                android:layout_height="24dp"
                android:layout_gravity="center"
                android:background="@drawable/ic_like_disabled"
                android:src="@{vm.post.likeFromUser ? @drawable/ic_like_enabled : @drawable/ic_like_disabled}" />

        </xyz.hanks.library.bang.SmallBangView>

        <TextView
            android:id="@+id/postLikesCount"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:text="@{vm.post.likes}"
            app:layout_constraintBottom_toBottomOf="@id/btnLike"
            app:layout_constraintStart_toEndOf="@id/btnLike"
            app:layout_constraintTop_toTopOf="@id/btnLike" />
```
but nothing happens. I understand why, but I have no idea how to fix this.
Please, can you upload advanced sample or give me a sign how can I do this?

**Comment by fraggjkee** [comment]
For such cases (when individual items are dynamic by themselves) it would be more natural & reasonable to use [ObservableField](https://developer.android.com/reference/android/databinding/ObservableField) which is a build-in part of the Android's DataBinding framework. One of the potential solutions may look like this:

1) your item-level VMs can expose `ObservableField`s instead of regular variables
2) these view models can update the state of any individual observable field it owns (in response to some user interaction for instance)
3) you use these observable fields in XML with no changes as if they were plain variables (thanks to the DataBinding framework).

Here's a quick example:

```
class FeedPostModel(privat val post: Post) {

    val likesCount = ObservableInt(post.likes)
    val isLiked = ObservableBoolean(post.likeFromUser)

    fun onLikeClick() {
        val currentValue = likesCount.get()
        likesCount.set(currentValue++)
    }
}
```

```
<TextView
    ...   
    android:text="@{vm.likesCount}" />           
```

**Comment by ghost** [comment]
Okay, it works fine, thank you. But what if I need to do something like this?

Sample from [official repo](https://github.com/hanks-zyh/SmallBang/blob/a6bc3b1220fc14d0f8e464236faa131446a68ac6/simple/src/main/java/xyz/hanks/smallbang/ListActivity.java#L71):
```java
holder.smallBang.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        int position = holder.getAdapterPosition();
        Item item = data.get(position);
        if (item.liked) {
            item.liked = false;
            holder.smallBang.setSelected(false);
        } else {
            item.liked = true;
            holder.smallBang.setSelected(true);
            holder.smallBang.likeAnimation();    <----- I wanna do this with DataBinding and call likeCallback from previous comment at the same time
        }
    }
});
```
Please, can you explain, how can I avoid saving the reference for `smallBang` view above and use your practice?
I tried to use custom BindingAdapter, but this didn't work

**Comment by fraggjkee** [comment]
Could you please clarify what was the issue with `BindingAdapter`? I believe this is the way to go: you should create a new adapter for `SmallBangView` which will invoke `likeAnimation()` method under the hood. This adapter could be triggered by some `ObservableBoolean` variable.

A simplified implementation:
```
@BindingAdapter("isLiked")
fun setLiked(view: SmallBangView, isLiked : Boolean) {
    view.selected = isLiked
    if (isLiked) view.likeAnimation()
}
```

https://developer.android.com/topic/libraries/data-binding/binding-adapters

**Comment by ghost** [comment]
Yes, I've tried the same
```kotlin 
@BindingAdapter("isLiked")
fun setLiked(view: SmallBangView?, isLiked : Boolean) {
    if (view != null) {
        view.isSelected = isLiked
        if (!isLiked) view.likeAnimation()  <--- error here
    }
}
```
but it gets me this error: 
```kotlin
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setScaleX(float)' on a null object reference
        at xyz.hanks.library.bang.SmallBangView.likeAnimation(SmallBangView.java:190)
        at xyz.hanks.library.bang.SmallBangView.likeAnimation(SmallBangView.java:181)
        at com.nowiwr01.languator.extensions.ViewExtensionsKt.setLiked(ViewExtensions.kt:84) // @BindingAdapter above
        at com.nowiwr01.languator.databinding.FeedItemBindingImpl.executeBindings(FeedItemBindingImpl.java:289)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:473)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:445)
        at com.fraggjkee.recycleradapter.DataBindingRecyclerAdapter.onBindViewHolder(DataBindingRecyclerAdapter.kt:32)
        at com.fraggjkee.recycleradapter.DataBindingRecyclerAdapter.onBindViewHolder(DataBindingRecyclerAdapter.kt:9)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:25466)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:763)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:426)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:105)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:247)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:117)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1532)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1607)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:763)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:426)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:105)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:247)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:117)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1532)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1607)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**I'm not sure that this is cause of your library**, but it works fine with default RecyclerView Adapter and I wanna figure out what the problem is so much

When I'm trying to like post, there is the following sequence of actions:
```kotlin
if (!isLiked) view.likeAnimation() // where likeAnimation is

public void likeAnimation() {
    likeAnimation(null); // where likeAnimation is
}

public void likeAnimation(Animator.AnimatorListener listener) {
    if (animatorSet != null) {
        animatorSet.cancel();
    }
    scaleView.setScaleX(0);  <---- error
    // .....
}

// but scaleView must be found at the measurement stage
@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
    if (scaleView == null) {
        scaleView = findScaleView(); // where findScaleView() is
    }
}

private View findScaleView() {
    for (int i = 0; i < getChildCount(); i++) {
        View child = getChildAt(i);
        if (isScaleView(child)) { // child != null in fact
            return child;
        }
    }
    throw new RuntimeException("must have one child in SmallBangView");
}
```

and my **feed_item.xml** with SmallBang is
```xml
<xyz.hanks.library.bang.SmallBangView
        android:id="@+id/btnLike"
        // ...
        app:isLiked="@{vm.isLiked()}"    <----- Trying to use custom BindingAdapter
        android:onClick="@{() -> vm.onLikeClick()}">

        <ImageView
            android:id="@+id/imageLike"
            // ....
            android:src="@{vm.isLiked() ? @drawable/ic_like_enabled : @drawable/ic_like_disabled}" />

</xyz.hanks.library.bang.SmallBangView>
```

If you think that the problem is not because of your library, then forget it, I have one more question in the next post :)

**Comment by ghost** [comment]
In my RecyclerView item I have ViewPager2 to show user VK attachments (photos)
Is it possible to save the state of ViewPager with your library? (I want to be able to get the last state of the picture to which the user has scrolled)

**Comment by fraggjkee** [comment]
Not sure if the problem has anything to do with the library but most likely it is related to the DataBinding framework at least. My guess is that your custom binding adapter gets invoked before `onMeasure` of that custom `SmallBangView` view for some reason. You should probably extend your binding adapter to include some defensive logic: it should check whether the view is ready to be animated or not. I'd start from the following:

- https://developer.android.com/reference/android/view/View#isAttachedToWindow()
- https://developer.android.com/reference/android/view/View#isInLayout()
- https://developer.android.com/reference/android/view/View#isLaidOut()

Alternatively, you could try using something specific methods/properties of the `SmallBangView` like `if (view.scaleView != null) ...`

```
@BindingAdapter("isLiked")
fun setLiked(view: SmallBangView?, isLiked : Boolean) {
    if (view != null && view.isAttachedToWindow) {
        view.isSelected = isLiked
        if (!isLiked) view.likeAnimation()
    }
}
```

I think it should be safe to skip some invocations of the adapter in such cases since there will be more calls to it later.




-----

> In my RecyclerView item I have ViewPager2 to show user VK attachments (photos)
> Is it possible to save the state of ViewPager with your library? (I want to be able to get the last state of the picture to which the user has scrolled)

I don't think adapters should be responsible for saving scroll state. Adapters have no idea about scroll events and don't receive any scroll-related callbacks. So I'd say  it should be handled somewhere outside of the adapter either with or without some 3rd party adapter library. However, you can store whatever makes sense for your needs inside adapter items and use that information from the view layer which has direct access to ViewPager / RecyclerView.

**Comment by ghost** [comment]
Oh, thank you, man, it works. My bad.

Yes, it's true
> Adapters have no idea about scroll events and don't receive any scroll-related callbacks.

But imo the simplest way to save ViewPager2 (inside of RecyclerView item) state is to create the *states* Map inside of RecyclerView Adapter, override `onViewRecycled()` and put in *states* map value (image position in ViewPager) by RecyclerView Adapter position. 

After that we can restore our states in `onBindViewHolder` - if we have value in *states* map by position then we can get it and set the actual ViewPager position, otherwise we set zero like actual position.

**I think this is my last question: Is this right way to do what I want?** It works, but I'm just curious about "best practice" to customize something. If you don’t think so, could you please suggest the correct way to do it?

**BindableRecyclerWithViewPagerAdapter**
```kotlin
private val states = mutableMapOf<Int, Int>()

override fun onBindViewHolder(holder: BindingViewHolder, position: Int) {
    with(holder) {
        getItem(position).bind(binding, states[position])  <--- here
        if (binding.hasPendingBindings()) {
            binding.executePendingBindings()
        }
    }
}

override fun onViewRecycled(holder: BindingViewHolder) {
    states[holder.adapterPosition] = holder.binding.root.findViewById<ViewPager2>(R.id.postViewPager).currentItem
}
```

**ViewPagerInstance**
```kotlin
interface ViewPagerInstance {
    fun setViewPagerPosition(position: Int)
}
```
**FeedPostModel**
```kotlin
class FeedPostModel(val post: Post): ViewPagerInstance {
    val viewPagerPosition = ObservableField(0)

    override fun setViewPagerPosition(position: Int) {
        viewPagerPosition.set(position)
    }    
}
```

**RecyclerItem**
```kotlin
data class RecyclerItem(val data: Any, @LayoutRes val layoutId: Int, val variableId: Int) {
    fun bind(binding: ViewDataBinding, pos: Int? = null) {
        if (data is ViewPagerInstance) {   <--- here
            data.setViewPagerPosition(pos ?: 0)
        }
        val isVariableFound = binding.setVariable(variableId, data)
        if (isVariableFound.not()) {
            throw IllegalStateException(buildErrorMessage(variableId, binding))
        }
    }
}
```

**feed_item.xml**
```xml
<androidx.viewpager2.widget.ViewPager2
        android:id="@+id/postViewPager"
        loadItems="@{vm.post.attachments}"
        // ...
        setPosition="@{vm.viewPagerPosition}" />  <-- here
```

**BindingAdapter**
```kotlin
@BindingAdapter("setPosition")
fun setPreviousItem(viewPager: ViewPager2, position: Int) {
    viewPager.currentItem = position
}
```

**Comment by fraggjkee** [comment]
I am not sure if it a good approach or not to be honest, the library is not currently designed for such use cases and doesn't provide any built-in support for this. But the original idea was to provide 1 universal adapter and `RecyclerItem` and your changes above kinda violate this original principle: you're hardcoding everything for 1 particular use case with ViewPager as recycler item and these additions aren't required for any other case apart from this (very specific) one.

I might consider extending the library in the future though to provide some callbacks for the adapter itself and its `RecyclerItem` to make such tweaks possible without forking/modifying the original source.

**Comment by ghost** [comment]
Okay, thank you for your time. I'll try to customize my solution.
We would be very happy to see these changes and the new part of "RecyclerView 2020" in the future :)
Good luck 👍
